### ISSUE TITLE
Multiple meta files behavior

### ISSUE THREAD

**Issue by pablogs9** [colcon/colcon-metadata#20]
Hi, I would like to know which is the default behavior when multiple `.meta` files are used when calling the build. For example if I call `colcon build --metas conf1.meta conf2.meta `  with the following files:

conf1.meta
```
{
    "names": {
        "package1": {
            "cmake-args": [
                "-DOPTION_1=1",
                "-DOPTION_2=2",
                "-DOPTION_3=3",
            ]
        }
    }
}
```

conf2.meta
```
{
    "names": {
        "package1": {
            "cmake-args": [
                "-DOPTION_2=22",
                "-DOPTION_4=4",
            ]
        }
    }
}
```

Are all the options being merged and duplicated ones being overwritted with order-based priority?

Thanks

**Comment by dirk-thomas** [comment]
> maybe the second one overwrites the first list

There is no custom merge logic atm. The entry from the second file overwrites the duplicate keys from the first file: https://github.com/colcon/colcon-metadata/blob/c4df07e1778647c078555c018aaaa9623106a817/colcon_metadata/package_discovery/colcon_meta.py#L89-L90

**Comment by pablogs9** [comment]
Thanks Dirk, really useful and clarifying.

It is ok for you to implement here a `cmake-args` merging logic or this task should be outside colcon?

I would be happy to contribute with a PR

**Comment by dirk-thomas** [comment]
Thanks for offering to help.

Since the metadata package doesn't know what kind of command line arguments exist the merge logic needs to be fairly generic - basically decide how to merge data based on their type. Please see #21 for a proposed patch and comment if that works for your use case.

**Comment by pablogs9** [comment]
Its ok for me. Thank you very much. How much time do you think it will take to see this changes on the  release once #21 is merged?
