### ISSUE TITLE
colcon.pkg do not use symlink-install

### ISSUE THREAD

**Issue by ldevillez** [colcon/colcon-metadata#34]
Hello,

I'm trying to create a `colcon.pkg` file to give default command line arguments to my package. I saw this issue: https://github.com/colcon/colcon-core/issues/111 but I still have some problems. I want to specify that my launch package use the option `--symlink-install`. When I do `colcon build --symlink-install`, I get effectively symlink on my package. When i try to put it in my `colcon.pkg` to affect only this package and not whole workspace, this option seems to be ignored

My `colcon.pkg` file:
```
{
  "symlink-install": true,
}
```

Can you help me find what I do wrong ? 
Thanks !

**Comment by cottsay** [comment]
We don't have the ability to specify symlink per-package, only per-invocation. You can use a `colcon_defaults.yaml` in your workspace root if you want symlinking enabled by default for that workspace, or a global `defaults.yaml` to enable it by default for every invocation of colcon.
