### ISSUE TITLE
Support file paths

### ISSUE THREAD

**Issue by miquelmassot** [colcon/colcon-metadata#35]
Currently, this plugin only supports "raw" github links. It does not allow users to specify a local (full or relative) path to a folder.

https://github.com/colcon/colcon-metadata/blob/6a9d8bd43e8baaceb84432e423e6874522ba75f2/colcon_metadata/subverb/add.py#L27

Could this be implemented?

**Comment by cottsay** [comment]
You can use `file://` URLs to do this. For example:
```
$ colcon metadata add local file://$PWD/src/colcon-metadata-repository/index.yaml
```

Note that metadata URLs are centrally configured and aren't tied to a particular colcon workspace, so there isn't a very strong reason to support relative paths. We'd need to convert them to an absolute path prior to storing the repository location anyway.
